version: "3.9"

services:

  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kaddem_db
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=mansouri.firas@esprit.tn
      - PGADMIN_DEFAULT_PASSWORD=firas
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

  # kaddem:
  #   image: firasmns/kaddem:latest
  #   container_name: kaddem
  #   ports:
  #     - "8082:8082"
  #   depends_on:
  #     - postgres

  nexus:
    image: sonatype/nexus3
    container_name: nexus3
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - "9000:9000"

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - monitoringNetwork

  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - monitoringNetwork

volumes:
  data:
  nexus_data:

networks:
  monitoringNetwork:
    driver: bridge